baseURL: https://juanmanuel.petrer.eu/
languageCode: en-us
build:
  writeStats: true
params:
  title: aafu theme
  author: Darshan Baral
  description: Website title
  copyright:
  theme:
    mainTheme: dark
    showAttribute: false
    singlePage: false
  favicons:
    use: false
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Juan Manuel"
    location: "Petrer, Alicante, España"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "#"
        title: LinkedIn
      - icon:
        url: "https://www.linkedin.com/in/juan-manuel-ruiz-mu%C3%B1oz/"
        title: StackOverflow
      - icon: fab fa-github
        url: "https://github.com/JuanManuelRM7"
        title: GitHub
      - icon:
        url: "#"
        title: ResearchGate
        #email
      - icon: fas fa-envelope
        url: "mailto:juanmanuel@petrer.eu"
        title: Email
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: Sobre mí
    icon: fas fa-user
    description: Soy un apasionado de la física y de las matemáticas. Siempre me ha interesado la problemática del cambio climático y es por ello por lo que creo que encuentro una mayor afinidad con los ámbitos relacionados con la meteorología o energías renovables. Actualmente me encuentro trabajando como investigador y desarrollador en inteligencia artificial, un campo con mucho potencial en multitud de sectores, especialmente en la lucha por paliar los efectos del cambio climático.
  experience:
    title: Experiencia
    icon: fas fa-briefcase
    list:
      - position: Data Scientist & AI Researcher
        dates: Junio 2024 - *Presente*
        company: AIR Institute
        url: "https://www.air-institute.org/"
        details: |1-
      - position: Investigador en Universidad Miguel Hernández
        dates: Enero 2024 - Julio 2024
        url: "#"
        company: Grupo SCOLAb
        url: "https://seneca.umh.es/"
        details: |1-
            - Técnicas Lagrangianas para la detección automática de situaciones de bloqueo atmosférico.
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Ph.D. in Subject
        college: University of State-City
        dates: 2013 - 2018
        thesis_title: "Effect of humans on other humans: a study of human behavior."
        thesis_url: "#"
      - degree: M.S. in Subject
        college: University of State-City
        dates: 2013 - 2018
        thesis_title: "Effect of humans on other humans: a study of human behavior."
        thesis_url: "#"
      - degree: B.S. in Subject
        college: University of State-City
        dates: 2004 - 2009
  publication:
    title: Publications
    icon: fas fa-book
    format:
      - date
      - title
      - authors
      - journal
    types:
      - Journal Articles
      - Proceedings
    list:
      - title: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        authors: "F Last, F Second, P secondary"
        date: "2018"
        journal: "Journal of Field 52 (16), 9033-9044"
        url: "#"
        type: Journal Articles
      - title: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        authors: "F Last, F Second, P secondary"
        date: "2018"
        journal: "Journal of Field 52 (16), 9033-9044"
        url: "#"
        type: Journal Articles
      - title: >-
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        authors: "F Last, F Second, P secondary"
        date: "2018"
        journal: "Journal of Field 52 (16), 9033-9044"
        url: "#"
        type: Proceedings
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Project 1
        url: "#"
        description: Description of the project
      - title: Project 2
        url: "#"
        description: Description of the project
      - title: Project 3
        url: "#"
        description: Description of the project
      - title: Project 4
        url: "#"
        description: Description of the project
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "Python"
        skillrating: 100
