baseURL: https://juanmanuel.petrer.eu/
languageCode: en-us
build:
  writeStats: true
params:
  title: Blog de Juan Manuel
  author: Juan Manuel
  description: Blog personal de Juan Manuel
  copyright:
  theme:
    mainTheme: null
    showAttribute: false
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Juan Manuel"
    location: "Petrer, Alicante"
    photo: profile.jpg
    position: "AI Researcher & Data Scientist"
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/juan-manuel-ruiz-mu%C3%B1oz/"
        title: LinkedIn
      - icon:
        url: "#"
        title: StackOverflow
      - icon: fab fa-github
        url: "https://github.com/JuanManuelRM7"
        title: GitHub
      - icon:
        url: "#"
        title: ResearchGate
        #email
      - icon: fas fa-envelope
        url: "mailto:juanmanuel@petrer.eu"
        title: Email
      - icon:
        url: "#"
        title: blablabla
        #orcid
      - icon: fab fa-orcid
        url: "https://orcid.org/0009-0008-7529-306X"
        title: ORCID
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: Sobre mí
    icon: fas fa-user
    description: Soy un apasionado de la física y de las matemáticas. Siempre me ha interesado la problemática del cambio climático y es por ello por lo que creo que encuentro una mayor afinidad con los ámbitos relacionados con la meteorología o energías renovables. Actualmente me encuentro trabajando como investigador y desarrollador en inteligencia artificial, un campo con mucho potencial en multitud de sectores, especialmente en la lucha por paliar los efectos del cambio climático.
  experience:
    title: Experiencia
    icon: fas fa-briefcase
    list:
      - position: Data Scientist & AI Researcher
        dates: Junio 2024 - *Presente*
        company: AIR Institute & Grupo de Investigación BISITE
        url: "https://www.air-institute.org/"
        details: |1-
            - Analizar y definir los requisitos del proyecto, diseñando y desarrollando soluciones de aprendizaje automático utilizando algoritmos de vanguardia.
            - Diseñar e implementar algoritmos de aprendizaje automático personalizados para una variedad de proyectos, incluyendo procesamiento del lenguaje natural, redes neuronales y visión computacional, entre otros.
            - Mantenerse al día con los últimos avances en investigación en diversos campos de la inteligencia artificial.
            - Escribir y revisar documentación técnica.
            - Reunirse con los clientes para comprender sus requisitos y adaptar las soluciones a sus necesidades.
            - Colaborar con otros miembros del equipo para lograr los objetivos del proyecto.
      - position: Investigador en Universidad Miguel Hernández
        dates: Enero 2024 - Julio 2024
        url: "#"
        company: Grupo SCOLAb
        url: "https://seneca.umh.es/"
        details: |1-
            - Desarrollo e investigación de técnicas Lagrangianas para la identificación automática de situaciones de bloqueo atmosférico.
            - Colaboración en otros proyectos del grupo relacionados con la física atmosférica.
  education:
    title: Educación
    icon: fas fa-graduation-cap
    list:
      - degree: Grado en Física
        college: Universidad de Alicante
        dates: 2020 - 2024
        thesis_title: "Un método lagrangiano para la identificación de situaciones de bloqueo atmosférico"
        thesis_url: "#"
      - degree: Grado en Matemáticas
        college: Universidad de Alicante
        dates: 2018 - 2023
      - degree: Estudiante SICUE en el grado en Física y grado en Matemáticas
        college: Universidad de Salamanca
        dates: 2022 - 2023

  publication:
    title: Publicaciones
    icon: fas fa-book
    format:
      - title
      - authors
    types:
      - En desarrollo
      - Publicado
    list:
      - title: AI-Powered Ontology-Based Architecture for Misinformation Detection in Fiction Works
        authors: "M. Arias-González, J. M. Ruiz Muñoz, P. Armenteros-Cosme, L. Isabel-Rodríguez, J. Curto-Hernández."
        type: En desarrollo
# project:
#   title: Proyectos
#   icon: fas fa-project-diagram
#   list:
#     - title: En desarrollo
#       url: "#"
#       description: 
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "Python"
        skillrating: 100
      - skill: "LaTeX"
        skillrating: 100
      - skill: "HYSPLIT"
        skillrating: 100
      - skill: "R"
        skillrating: 80
      - skill: "SQL"
        skillrating: 80
      - skill: "MATLAB"
        skillrating: 70
      - skill: "AWS"
        skillrating: 60

